[build]
  command = "vite build"
  publish = "dist/client"
[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
<meta name="google-site-verification" content="7c1XlDdyEhBDILhPkFvxKQXSn6rZlmfYKVRt8rBBqnk" />
